-- =============================================================
-- WorkforceMS Recruitment Module — Supabase Schema
-- Source: BlindHire (Ebosetale-Victor123)
-- For merger with WorkforceIQ shared Supabase project
-- All tables use IF NOT EXISTS — safe to run on existing DBs
-- =============================================================

-- -------------------------------------------------------------
-- SECTION 1: RECRUITMENT TABLES
-- These are the core tables used by workforcems-recruitment app
-- WorkforceIQ engineers: these are the tables you are merging with
-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS jobs (
    id                  uuid NOT NULL DEFAULT gen_random_uuid(),
    title               text NOT NULL,
    department          text NOT NULL,
    description         text,
    requirements        text,
    type                text DEFAULT 'full-time'::text,
    status              text DEFAULT 'open'::text,
    created_at          timestamp with time zone DEFAULT now(),
    -- Additional fields recommended for WorkforceMS merger:
    salary_range        text,
    location            text,
    closing_date        date,
    employment_type     text,
    PRIMARY KEY (id)
);

COMMENT ON TABLE jobs IS 
'Job postings. Used by WorkforceMS Recruitment module and WorkforceIQ ATS.';

-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS applications (
    id                      uuid NOT NULL DEFAULT gen_random_uuid(),
    job_id                  uuid REFERENCES jobs(id) ON DELETE SET NULL,
    candidate_name          text NOT NULL,
    candidate_email         text NOT NULL,
    candidate_phone         text,
    candidate_age           integer,
    candidate_gender        text,
    candidate_school        text,
    cv_text                 text,
    skills                  text[],
    stage                   text DEFAULT 'applied'::text,
    blind_score             numeric,
    ai_summary              text,
    is_blinded              boolean DEFAULT false,
    created_at              timestamp with time zone DEFAULT now(),
    updated_at              timestamp with time zone DEFAULT now(),
    original_cv             text,
    application_reference   text,
    source                  text DEFAULT 'manual'::text,
    years_experience        integer,
    applicant_role          text,
    phone                   text,
    cv_file_url             text,
    PRIMARY KEY (id)
);

COMMENT ON TABLE applications IS 
'Candidate applications. is_blinded controls anonymisation. 
original_cv stores raw CV, cv_text stores anonymised version.
source: manual | careers_portal | import';

COMMENT ON COLUMN applications.is_blinded IS
'When true: candidate_name, candidate_email, candidate_phone, 
candidate_school are hidden from recruiters until manually revealed.';

COMMENT ON COLUMN applications.blind_score IS
'AI-generated score 0-100 based on CV vs role match. 
Generated by Groq llama-3.1-8b-instant via Blind Screener.';

-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS feedback (
    id          uuid NOT NULL DEFAULT gen_random_uuid(),
    category    text NOT NULL,
    message     text,
    created_at  timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

COMMENT ON TABLE feedback IS 
'Anonymous feedback submissions. No reporter_id by design — 
identity cannot be recovered even with direct DB access.';

-- -------------------------------------------------------------
-- SECTION 2: HR OPERATIONS TABLES
-- These exist in BlindHire but are NOT used by the recruitment module
-- Included here for WorkforceIQ engineers to review for conflicts
-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS employees (
    id                  uuid NOT NULL DEFAULT gen_random_uuid(),
    employee_id         text NOT NULL,
    first_name          text NOT NULL,
    last_name           text NOT NULL,
    email               text NOT NULL,
    phone               text,
    department          text NOT NULL,
    role                text NOT NULL,
    employment_type     text DEFAULT 'full-time'::text,
    status              text DEFAULT 'active'::text,
    salary              numeric,
    hire_date           date,
    avatar_url          text,
    bank_name           text,
    account_number      text,
    next_of_kin         text,
    created_at          timestamp with time zone DEFAULT now(),
    personal_email      text,
    date_of_birth       date,
    gender              text,
    middle_name         text,
    state_of_origin     text,
    address             text,
    PRIMARY KEY (id)
);

COMMENT ON TABLE employees IS
'Core employee records. WorkforceIQ engineers: check for conflicts 
with your own employees table before merging — reconcile column 
differences before running migrations on shared project.';

-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS departments (
    id                  uuid NOT NULL DEFAULT gen_random_uuid(),
    name                text NOT NULL,
    head_of_department  text,
    created_at          timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS attendance (
    id              uuid NOT NULL DEFAULT gen_random_uuid(),
    employee_id     uuid REFERENCES employees(id) ON DELETE CASCADE,
    date            date NOT NULL,
    clock_in        time without time zone,
    clock_out       time without time zone,
    status          text DEFAULT 'present'::text,
    hours_worked    numeric,
    created_at      timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS leave_requests (
    id              uuid NOT NULL DEFAULT gen_random_uuid(),
    employee_id     uuid REFERENCES employees(id) ON DELETE CASCADE,
    leave_type      text NOT NULL,
    start_date      date NOT NULL,
    end_date        date NOT NULL,
    reason          text,
    status          text DEFAULT 'pending'::text,
    created_at      timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS onboarding (
    id                  uuid NOT NULL DEFAULT gen_random_uuid(),
    employee_id         uuid REFERENCES employees(id) ON DELETE CASCADE,
    task                text NOT NULL,
    category            text,
    completed           boolean DEFAULT false,
    due_date            date,
    created_at          timestamp with time zone DEFAULT now(),
    task_type           text DEFAULT 'checkbox'::text,
    requires_document   boolean DEFAULT false,
    document_url        text,
    document_name       text,
    completed_at        timestamp with time zone,
    notes               text,
    completed_by        text DEFAULT 'employee'::text,
    PRIMARY KEY (id)
);

-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS onboarding_templates (
    id                  uuid NOT NULL DEFAULT gen_random_uuid(),
    department          text NOT NULL,
    task_name           text NOT NULL,
    task_type           text NOT NULL,
    description         text,
    due_days_after_hire integer DEFAULT 7,
    requires_document   boolean DEFAULT false,
    created_at          timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS payroll (
    id              uuid NOT NULL DEFAULT gen_random_uuid(),
    employee_id     uuid REFERENCES employees(id) ON DELETE CASCADE,
    month           text NOT NULL,
    year            integer NOT NULL,
    basic_salary    numeric,
    allowances      numeric DEFAULT 0,
    deductions      numeric DEFAULT 0,
    tax             numeric DEFAULT 0,
    pension         numeric DEFAULT 0,
    net_pay         numeric,
    status          text DEFAULT 'pending'::text,
    created_at      timestamp with time zone DEFAULT now(),
    paid_at         timestamp with time zone,
    transaction_id  uuid,
    PRIMARY KEY (id)
);

-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS transactions (
    id                      uuid NOT NULL DEFAULT gen_random_uuid(),
    employee_id             uuid REFERENCES employees(id) ON DELETE SET NULL,
    payroll_id              uuid REFERENCES payroll(id) ON DELETE SET NULL,
    amount                  numeric NOT NULL,
    bank_name               text,
    account_number          text,
    account_name            text,
    paystack_reference      text,
    paystack_recipient_code text,
    status                  text DEFAULT 'pending'::text,
    failure_reason          text,
    paid_at                 timestamp with time zone,
    created_at              timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

COMMENT ON TABLE transactions IS
'Paystack payment records. Status: pending | success | failed. 
paystack_reference links to live Paystack dashboard.';

-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS performance_records (
    id                      uuid NOT NULL DEFAULT gen_random_uuid(),
    employee_id             uuid REFERENCES employees(id) ON DELETE CASCADE,
    month                   text,
    year                    integer,
    attendance_score        numeric,
    task_completion_score   numeric,
    manager_rating          numeric,
    overall_score           numeric,
    notes                   text,
    created_at              timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tasks (
    id              uuid NOT NULL DEFAULT gen_random_uuid(),
    employee_id     uuid REFERENCES employees(id) ON DELETE CASCADE,
    title           text,
    status          text DEFAULT 'pending'::text,
    due_date        date,
    completed_at    timestamp with time zone,
    created_at      timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS queries (
    id              uuid NOT NULL DEFAULT gen_random_uuid(),
    employee_id     uuid REFERENCES employees(id) ON DELETE CASCADE,
    ticket_number   text,
    type            text NOT NULL,
    category        text NOT NULL,
    subject         text NOT NULL,
    message         text NOT NULL,
    amount          numeric,
    receipt_note    text,
    status          text DEFAULT 'open'::text,
    hr_response     text,
    resolved_at     timestamp with time zone,
    created_at      timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- =============================================================
-- ROW LEVEL SECURITY NOTES FOR WORKFORCEIQ ENGINEERS
-- =============================================================
-- BlindHire currently does not enforce RLS on all tables.
-- When merging into shared Supabase project, apply RLS policies
-- matching WorkforceIQ's existing pattern:
--
-- For recruitment tables (jobs, applications, feedback):
--   - Public read on jobs where status = 'open' (careers portal)
--   - Authenticated HR only for all write operations
--   - is_blinded = true rows: never expose candidate_name,
--     candidate_email, candidate_phone, candidate_school
--     in API responses to non-admin roles
--
-- Suggested RLS for jobs (public careers page):
--   CREATE POLICY "Public can view open jobs"
--   ON jobs FOR SELECT
--   USING (status = 'open');
--
-- Suggested RLS for applications (blind enforcement):
--   CREATE POLICY "HR can view all applications"
--   ON applications FOR SELECT
--   TO authenticated
--   USING (true);
-- =============================================================

-- =============================================================
-- MERGE CONFLICT CHECKLIST FOR WORKFORCEIQ ENGINEERS
-- =============================================================
-- Before running this on the shared Supabase project, check:
--
-- 1. employees table — does WorkforceIQ have different columns?
--    BlindHire has: state_of_origin, address, middle_name, 
--    personal_email, date_of_birth, gender
--    Reconcile before merging.
--
-- 2. jobs table — BlindHire uses 'type' for employment type,
--    WorkforceIQ may use 'employment_type'. Align column name.
--    Also add: salary_range, location, closing_date if missing.
--
-- 3. departments table — both systems likely have this.
--    Check if WorkforceIQ uses department_id as FK in employees
--    vs BlindHire which stores department as plain text.
--
-- 4. attendance table — WorkforceIQ has QR-based attendance
--    with more fields. BlindHire version is simpler.
--    Use WorkforceIQ's version as the primary.
--
-- 5. feedback table — BlindHire feedback has no reporter_id
--    by design (anonymous). WorkforceIQ anonymous reports use
--    NULL reporter_id with tracking tokens. These are different
--    tables serving different purposes — keep both.
-- =============================================================
